<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="prestation.CSS">
</head>
<body>
      <!--debut de l'entete-->
  <header>
    <center>
        <marquee behavior="right" direction="left">
            <h3>⭐⭐Bienvenue au Palais Royal⭐⭐</h3>
        </marquee>
    </center>
    <!--logo-->
     <div class="logo"> 
        <p> <a href="#">
              <span class="corone">👑</span><br>
              <span class="DB">P&R</span><br>
              <span class="nomhotel">Palais  Royal</span>
            </a>
        </p>
    </div> 
    <!--menu (home..)-->
    <ul class="navmenu">
             <li><a href="index.PHP">Accueil</a></li>
          <div>
             <li><a  href="prestation.PHP">prestations</a></li>
           </div>
               <li><a href="reservation.PHP">reservation</a></li>
            <li><a href="contact.PHP">contact</a></li>
            <li><a href="inscription.PHP">inscription</a></li>
    </ul>
    <!--image user-->
    <div class="img1">
      <a href="inscription.PHP">
        <img src="image\user.jpg">
      </a>
    </div>
</header>
<!-- image du header-->
<div class="imag">
  <img src="image\image11.jpg">
</div>
  <!-- text 1-->
    <section class="tex1">
      <div class="text1">
        <h3><span>P</span>alais <span>R</span>oyal</h3>
        <h4>💙VOUS PROPOSE UNE DIVERSITE D'HOTELS</h4>
        <p >💙vous satisfaire c'est notre priorité</p>
    </div>
    </section>
   <!--text2--->
    <h2 class="text-h2"> <span>P</span>résentation de notre service </h2>
    <br>
    <h4 class="text-h4">💙<span>Palais & Royal :</span> une variété d'hôtels pour votre plaisir</h4>
     <!-- deuxieme image--->
    <div class="img3">
      <img src="image/image4.jpg">
    </div>
    <br>
    <div class="img4">
      <img src="image/image7.jpg">
    </div>
    <nav>  
      <!--presentation du service-->
      <h1 >💙 <span>A</span> PROPOS DE NOUS</h1>
      <br>
        <p>Palais Royal est une agence spécialisée dans la gestion et la réservation de séjour hôtelerie de luxe 
          .nous nous engageons à offrir à nos clients des expériences uniques et mémorables,adaptées à leurs besoins 
          spécifiques et à leurs désirs de confort et découverte.
          la valeur première que nous mettons en avant, c’est d’assure un confort irreprochable à nos client
          l’importance de redonner
         à tous nos clients l’amour de soi-même.Nous nous sommes lancées ensemble en 2024 avec pour projet de 
         créer palais royal pour embellir nos clients grâce a notre selection des meuilleurs hôtels.  
       </p>  
        <br>
      <h1>💙<span>S</span>ERVICES PROPOSES</h1>
         <br>
         <p>
          <h4> 1.Réservation de chambres:</h4>
          Accès à une vaste sélection d'hôtels de luxe à travers le monde.
          Possibilité de réserver des suites et des chambres avec vue panoramique, 
          des équipements haut de gamme, et des services personnalisés.
          <h4>2.Organisation de séjours sur mesure :</h4>
          Création de packages de vacances personnalisés 
          incluant hébergement, transport, activités et excursions.
          Conseils de voyage et recommandations sur les meilleures destinations et attractions locales.
          <h4>3.Gestion d'événements : </h4>
          Planification et coordination de mariages, conférences,
           et autres événements spéciaux dans des lieux prestigieux.
          Services de traiteur, décoration, et divertissement pour assurer le succès de chaque événement.
          <h4>5.Conciergerie de luxe :</h4>
          Services de conciergerie disponibles 24/7 pour répondre 
          à toutes les demandes des clients, qu'il s'agisse de réservations de restaurants, de billets 
          de spectacles, ou de services de transport privé.
          Assistance personnalisée pour les besoins spécifiques des clients, y compris
           les demandes spéciales et les préférences alimentaires.
          <h4>6.Offres exclusives et programmes de fidélité :</h4>
          Accès à des offres spéciales, 
          des réductions exclusives, et des avantages supplémentaires pour nos membres.
          Programme de fidélité récompensant les clients réguliers avec des nuits gratuites, 
          des surclassements, et des services VIP.
          Pourquoi choisir Palais Rôyal ?
          <h4>7.Expertise et expérience :</h4>
          Avec plusieures années d'expérience dans l'industrie hôtelière
          , nous avons développé une connaissance approfondie des meilleurs hôtels et destinations du monde.
      </nav>   
<br>
<!--pied de page-->
<footer>
    <!--la class contenu du foote-->
   <div class="contenu-footer">
      <div class=" bloc footer-plan">
         <h3>Plan du site</h3>
         <ul class="liste-Service">
         <li><a href="index.PHP">Acceuil</a></li>
             <br>
             <li><a  href="prestation.PHP">prestations</a></li>
              <br>
             <li><a href="reservation.PHP">Reservation</a></li>
             <br>
             <li><a href="contact.PHP">Contact</a></li>
             <br>
             <li><a href="inscription.PHP">inscription</a></li>
         </ul>
      </div>
      <div class=" bloc footer-contact">
        <h3>Restons en contact</h3>
        <p>📲Tel 1: 52-87-50-41</p>
        <br>
        <p>📲Tel 2: 56-06-41-93</p>
        <br>
        <!--email-->
        <p><a href="mailto:decidaisomar@gmail.com" class="email">decidaisomar@gmail.com</a></p>
         <!--image footer--> 
         <br>
        <div class="im1"><img src="image\logo.jpg"></div>
      </div>
      <div class=" bloc footer-horaire">
        <h3>Nos Horaires</h3>
         <ul class="liste-horaire">
           <li>✔️ Lun 03h-20h</li>
           <br>
           <li>✔️ Mar 02h-22h</li>
           <br>
           <li>✔️ Mer 04h-19h</li>
           <br>
           <li>✔️Jeu 01h-21h</li>
           <br>
           <li>✔️ Ven 04h-00h</li>
           <br>
           <li>✔️ sam 05h-23h</li>
           <br>
           <li>✔️ dim 05h-18h</li>
         </ul>
      </div>
      <div class=" bloc footer-reseaux">
         <h3>Nos réseaux</h3>
         <!--les media-->
         <ul class="liste-media">
             <li><a href=" https://chat.whatsapp.com/LtbxbuFx7T59jWL2gUSONr" target="_blank"><img src="image/whatsapp.jpg"> <br>whatsapp</a></li>
             <li><a href="https://www.facebook.com/profile.php?id=61561028142293 " target="_blank"><img src="image/facebook.jpg"> <br>facebook </a></li>
             <li><a href="https://www.instagram.com/company_royal_palace?igsh=dWhlMmVoNmdreTVl" target="_blank"><img src="image/instagrame.jpg"> <br>instagrame</a></li>
          </ul>

      </div>
      <div class=" bloc footer-menbre">
         <h3>Menbres groupe</h3>
          <ul class="liste-menbre">
          <li><span>1.</span>Dzidziwu Dylan Omar</li>
             <br>
             <li><span>2.</span>DIARRA KEYLA LESLIE</li>
             <br>
             <li><span>3.</span>DEGBO-HOUMEY WISDOM MARCEL</li>
             <br>
             <li><span>4.</span>NIKIEMA ELVIS JETHRO</li>
             <br>
             <li><span>5.</span> MAIGA ABDOUL GABIROU MOUSSA</li>
             <br>
             <li><span>6.</span> OUEDRAOGO PUSDBA GILBERTINE</li>
          </ul>
      </div>
    </div>
    <!--la date-->
      <div class="date">
          <p>copyright : 2024</p>
      </div>
    <br>
</footer>
</div>
</body>
</html>