<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="reservation.CSS">
  </head>
<body>
  <!--debut de l'entete-->
  <header>
    <center>
        <marquee behavior="right" direction="left">
            <h3>⭐⭐Bienvenue au Palais Royal⭐⭐</h3>
        </marquee>
    </center>
    <!--logo-->
     <div class="logo"> 
        <p> <a href="#">
              <span class="corone">👑</span><br>
              <span class="DB">P&R</span><br>
              <span class="nomhotel">Palais  Royal</span>
            </a>
        </p>
    </div> 
    <!--menu (home..)-->
    <ul class="navmenu">
            <li><a href="index.PHP">Accueil</a></li>
            <li><a  href="prestation.PHP">prestations</a></li>
      <div>
         <li><a href="reservation.PHP">reservation</a></li>
      </div>  
         <li><a href="contact.PHP">contact</a></li>
         <li><a  href="inscription.PHP">inscription</a></li>
    </ul>
     <!--image user-->
    <div class="img1">
      <a href="inscription.PHP"><img src="image\user.jpg"></a>
    </div>
</header>
<br>
<!-- video du header-->
<div class="video1">
  <video autoplay="autoplay" muted="" loop="infinite" src="video\1.mp4" width="100%"
  height="10%"></video>
</div>
 <!-- text 1-->
  <div class="text1">
    <h4><span>P</span>alais <span>R</span>oyal (Burkina Faso)</h4>
    <h5>💙Le Luxe à Votre Portée</h5>
    <p>💙Votre clé pour des séjours inoubliables</p>
</div>
<!--corp du site--->
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<!--corp du site partie nav--->
 <nav>
                 
<section class="section__container">
  <br>
  <br>
  <br>
  <h2><span>N</span>otre selection des mellieurs hôtels:</h2>
  <br>
  <h2 class="section__header">💙💙LES HOTELS POPULAIRES💙💙<br>💙💙 BANFORA💙💙</h2>
  <div class="popular__grid">
    <div class="popular__card">
      <img src="image\H4.jpg"/>
      <div class="popular__content">
        <div class="popular__card__header">
          <h4>Cascade palace hôtel</h4>
          <h4>⭐⭐⭐⭐</h4>
        </div>
        <button><a href="remplir_reser.PHP">Reserver</a></button>
        <p> Banfora, Burkina Faso</p>
      </div>
    </div>
    <div class="popular__card">
      <img src="image\H5.jpg"/>
      <div class="popular__content">
        <div class="popular__card__header">
          <h4>Check  hôtel </h4>
          <h4>⭐⭐⭐⭐</h4>
        </div>
        <button><a href="remplir_reser.PHP">Reserver</a></button>
        <p> Banfora, Burkina Faso</p>
      </div>
    </div>
    <div class="popular__card">
      <img src="image\H8"/>
      <div class="popular__content">
        <div class="popular__card__header">
          <h4>la Case de Marion</h4>
          <h4>⭐⭐⭐⭐⭐</h4>
        </div>
        <!--corp du site partie boutton--->
        <button><a href="remplir_reser.PHP">Reserver</a></button>

        <p> Banfora, Burkina Faso</p>
      </div>
    </div>
    <div class="popular__card">
      <img src="image\1.jpg"/>
      <div class="popular__content">
        <div class="popular__card__header">
          <h4>Chambre de l'hôtel ci-dessus</h4>
          <h4>XOF44900</h4>
        </div>
         <!--corp du site partie boutton--->
        <button><a href="remplir_reser.PHP">Reserver</a></button>

        <p>  Banfora, Burkina Faso</p>
      </div>
    </div>
    <div class="popular__card">
      <img src="image\2.jpg"/>
      <div class="popular__content">
        <div class="popular__card__header">
          <h4>Chambre de l'hôtel ci-dessus</h4>
          <h4>XOF64900</h4>
        </div>
         <!--corp du site partie boutton--->
        <button><a href="remplir_reser.PHP">Reserver</a></button>
        
        <p>  Banfora, Burkina Faso</p>
      </div>
    </div>
    <div class="popular__card">
      <img src="image\3.jpg"/>
      <div class="popular__content">
        <div class="popular__card__header">
          <h4>Chambre de l'hôtel ci-dessus</h4>
          <h4>XOF54900</h4>
        </div>
         <!--corp du site partie boutton--->
        <button><a href="remplir_reser.PHP">Reserver</a></button>

        <p>  Banfora, Burkina Faso</p>
      </div>
    </div>
  </div>
</section>

<section class="section__container">
  <br>
  <h2 class="section__header">💙💙LES HOTELS POPULAIRES💙💙<br> 💙💙A OUAGADOUGOU💙💙</h2>
  <div class="popular__grid">
    <div class="popular__card">
      <img src="image\H1.jpg"/>
      <div class="popular__content">
        <div class="popular__card__header">
          <h4>Bravia hôtel</h4>
          <h4>⭐⭐⭐⭐</h4>
        </div>
         <!--corp du site partie boutton--->
        <button><a href="remplir_reser.PHP">Reserver</a></button>

        <p> Ouagadougou, Burkina Faso</p>
      </div>
    </div>
    <div class="popular__card">
      <img src="image\H2.jpg"/>
      <div class="popular__content">
        <div class="popular__card__header">
          <h4>Splendid hôtel</h4>
          <h4>⭐⭐⭐⭐</h4>
        </div>
         <!--corp du site partie boutton--->
        <button><a href="remplir_reser.PHP">Reserver</a></button>

        <p> Ouagadougou, Burkina Faso</p>
      </div>
    </div>
    <div class="popular__card">
      <img src="image\H3.jpg"/>
      <div class="popular__content">
        <div class="popular__card__header">
          <h4>Faso hôtel</h4>
          <h4>⭐⭐⭐</h4>
        </div>
         <!--corp du site partie boutton--->
        <button><a href="remplir_reser.PHP">Reserver</a></button>

        <p> Ouagadougou, Burkina Faso</p>
      </div>
    </div>
    <div class="popular__card">
      <img src="image\4.jpg"/>
      <div class="popular__content">
        <div class="popular__card__header">
          <h4>Chambre de l'hôtel ci-dessus</h4>
          <h4>XOF40000</h4>
        </div>
         <!--corp du site partie boutton--->
        <button><a href="remplir_reser.PHP">Reserver</a></button>

        <p>Ouagadougou, Burkina Faso</p>
      </div>
    </div>
    <div class="popular__card">
      <img src="image\5.jpg"/>
      <div class="popular__content">
        <div class="popular__card__header">
          <h4>Chambre de l'hôtel ci-dessus</h4>
          <h4>XOF65000</h4>
        </div>
             <!--corp du site partie boutton--->
        <button><a href="remplir_reser.PHP">Reserver</a></button>

        <p>Ouagadougou, Burkina Faso</p>
      </div>
    </div>
    <div class="popular__card">
      <img src="image\6.jpg"/>
      <div class="popular__content">
        <div class="popular__card__header">
          <h4>Chambre de l'hôtel ci-dessus</h4>
          <h4>XOF44900</h4>
        </div>
         <!--corp du site partie boutton--->
        <button><a href="remplir_reser.PHP">Reserver</a></button>

        <p>Ouagadougou, Burkina Faso</p>
      </div>
    </div>
  </div>
</section>

<section class="section__container">
  <br>
  <br>
  <h2 class="section__header">💙💙LES HOTELS POPULAIRES💙💙 <br> 💙💙A BOBO DIOULASSO💙💙</h2>
  <div class="popular__grid">
    <div class="popular__card">
      <img src="image\H9.jpg"/>
      <div class="popular__content">
        <div class="popular__card__header">
          <h4>Sissiman hôtel</h4>
          <h4>⭐⭐⭐⭐</h4>
        </div>
         <!--corp du site partie boutton--->
        <button><a href="remplir_reser.PHP">Reserver</a></button>

        <p>Bobo dioulasso, Burkina Faso</p>
      </div>
    </div>
    <div class="popular__card">
      <img src="image\H7.jpg"/>
      <div class="popular__content">
        <div class="popular__card__header">
          <h4>L'auberge hôtel</h4>
          <h4>⭐⭐⭐⭐</h4>
        </div>
         <!--corp du site partie boutton--->
        <button><a href="remplir_reser.PHP">Reserver</a></button>

        <p>Bobo dioulasso, Burkina Faso</p>
      </div>
    </div>
    <div class="popular__card">
      <img src="image/H10"/>
      <div class="popular__content">
        <div class="popular__card__header">
          <h4>Pacific  hôtel Bobo </h4>
          <h4>⭐⭐⭐⭐</h4>
        </div>
         <!--corp du site partie boutton--->
        <button><a href="remplir_reser.PHP">Reserver</a></button>

        <p>Bobo dioulasso, Burkina Faso</p>
      </div>
    </div>
    <div class="popular__card">
      <img src="image\7.jpg"/>
      <div class="popular__content">
        <div class="popular__card__header">
          <h4>Chambre de l'hôtels ci-dessus</h4>
          <h4>XOF70000</h4>
        </div>
         <!--corp du site partie boutton--->
        <button><a href="remplir_reser.PHP">Reserver</a></button>

        <p>Bobo dioulasso, Burkina Faso</p>
      </div>
    </div>
    <div class="popular__card">
      <img src="image\8.jpg"/>
      <div class="popular__content">
        <div class="popular__card__header">
          <h4>Chambre de l'hôtels ci-dessus</h4>
          <h4>XOF74000</h4>
        </div>
         <!--corp du site partie boutton--->
        <button><a href="remplir_reser.PHP">Reserver</a></button>

        <p>Bobo dioulasso, Burkina Faso</p>
      </div>
    </div>
    <div class="popular__card">
      <img src="image\9.jpg"/>
      <div class="popular__content">
        <div class="popular__card__header">
          <h4>Chambre de l'hôtels ci-dessus</h4>
          <h4>XOF65700</h4>
        </div>
         <!--corp du site partie boutton--->
        <button><a href="remplir_reser.PHP">Reserver</a></button>

        <p>Bobo dioulasso, Burkina Faso</p>
      </div>
    </div>
  </div>
</section>


<section class="section__container">
  <br>
  <br>
  <br>
  <h2 class="section__header">💙💙LES HOTELS POPULAIRES💙💙<br> 💙💙A KOUDOUGOU💙💙</h2>
  <div class="popular__grid">
    <div class="popular__card">
      <img src="image\H11.jpeg"/>
      <div class="popular__content">
        <div class="popular__card__header">
          <h4>Excellence Hôtel</h4>
          <h4>⭐⭐⭐⭐</h4>
        </div>
        <button><a href="remplir_reser.PHP">Reserver</a></button>
        <p> Koudougou Burkina Faso</p>
      </div>
    </div>
    <div class="popular__card">
      <img src="image\H12.jpeg"/>
      <div class="popular__content">
        <div class="popular__card__header">
          <h4>Splendid Hôtel </h4>
          <h4>⭐⭐⭐⭐</h4>
        </div>
        <button><a href="remplir_reser.PHP">Reserver</a></button>
        <p> Koudougou, Burkina Faso</p>
      </div>
    </div>
    <div class="popular__card">
      <img src="image\H13"/>
      <div class="popular__content">
        <div class="popular__card__header">
          <h4>Ramonwende Hôtel</h4>
          <h4>⭐⭐⭐⭐</h4>
        </div>
        <!--corp du site partie boutton--->
        <button><a href="remplir_reser.PHP">Reserver</a></button>

        <p> Koudougou, Burkina Faso</p>
      </div>
    </div>
    <div class="popular__card">
      <img src="image\C1.jpeg"/>
      <div class="popular__content">
        <div class="popular__card__header">
          <h4>Chambre de l'hôtel ci-dessus</h4>
          <h4>XOF40000</h4>
        </div>
         <!--corp du site partie boutton--->
        <button><a href="remplir_reser.PHP">Reserver</a></button>

        <p>  Koudougou, Burkina Faso</p>
      </div>
    </div>
    <div class="popular__card">
      <img src="image\C2.jpeg"/>
      <div class="popular__content">
        <div class="popular__card__header">
          <h4>Chambre de l'hôtel ci-dessus</h4>
          <h4>XOF54000</h4>
        </div>
         <!--corp du site partie boutton--->
        <button><a href="remplir_reser.PHP">Reserver</a></button>
        
        <p>  Koudougou, Burkina Faso</p>
      </div>
    </div>
    <div class="popular__card">
      <img src="image\C3.jpeg"/>
      <div class="popular__content">
        <div class="popular__card__header">
          <h4>Chambre de l'hôtel ci-dessus</h4>
          <h4>XOF40000</h4>
        </div>
         <!--corp du site partie boutton--->
        <button><a href="remplir_reser.PHP">Reserver</a></button>

        <p>  Koudougou, Burkina Faso</p>
      </div>
    </div>
  </div>
</section>
<section class="section__container">
  <br>
  <br>
  <br>
  <h2 class="section__header">💙💙LES HOTELS POPULAIRES💙💙<br> 💙💙A TENKODOGO💙💙</h2>
  <div class="popular__grid">
    <div class="popular__card">
      <img src="image\H14.jpeg"/>
      <div class="popular__content">
        <div class="popular__card__header">
          <h4>Laafi hôtel</h4>
          <h4>⭐⭐⭐⭐</h4>
        </div>
        <button><a href="remplir_reser.PHP">Reserver</a></button>
        <p> Tenkodogo, Burkina Faso</p>
      </div>
    </div>
    <div class="popular__card">
      <img src="image\H15.jpeg"/>
      <div class="popular__content">
        <div class="popular__card__header">
          <h4>Tiéba  hôtel </h4>
          <h4>⭐⭐⭐⭐</h4>
        </div>
        <button><a href="remplir_reser.PHP">Reserver</a></button>
        <p> Tenkodogo, Burkina Faso</p>
      </div>
    </div>
    <div class="popular__card">
      <img src="image\H16.jpg"/>
      <div class="popular__content">
        <div class="popular__card__header">
          <h4>Djouma Hôtel</h4>
          <h4>⭐⭐⭐</h4>
        </div>
        <!--corp du site partie boutton--->
        <button><a href="remplir_reser.PHP">Reserver</a></button>

        <p> Tenkodogo, Burkina Faso</p>
      </div>
    </div>
    <div class="popular__card">
      <img src="image\C4.jpeg"/>
      <div class="popular__content">
        <div class="popular__card__header">
          <h4>Chambre de l'hôtel ci-dessus</h4>
          <h4>XOF51900</h4>
        </div>
         <!--corp du site partie boutton--->
        <button><a href="remplir_reser.PHP">Reserver</a></button>

        <p>  Tenkodogo, Burkina Faso</p>
      </div>
    </div>
    <div class="popular__card">
      <img src="image\C5.jpg"/>
      <div class="popular__content">
        <div class="popular__card__header">
          <h4>Chambre de l'hôtel ci-dessus</h4>
          <h4>XOF50000</h4>
        </div>
         <!--corp du site partie boutton--->
        <button><a href="remplir_reser.PHP">Reserver</a></button>
        
        <p>  Tenkodogo, Burkina Faso</p>
      </div>
    </div>
    <div class="popular__card">
      <img src="image\C6.jpeg"/>
      <div class="popular__content">
        <div class="popular__card__header">
          <h4>Chambre de l'hôtel ci-dessus</h4>
          <h4>XOF39900</h4>
        </div>
         <!--corp du site partie boutton--->
        <button><a href="remplir_reser.PHP">Reserver</a></button>

        <p>  Tenkodogo, Burkina Faso</p>
      </div>
    </div>
  </div>
</section>
<section class="section__container">
  <br>
  <br>
  <br>
  <h2 class="section__header">💙💙LES HOTELS POPULAIRES💙💙<br> 💙💙A KAYA💙💙</h2>
  <div class="popular__grid">
    <div class="popular__card">
      <img src="image\H17.jpg"/>
      <div class="popular__content">
        <div class="popular__card__header">
          <h4>Kaziendé Hôtel</h4>
          <h4>⭐⭐⭐</h4>
        </div>
        <button><a href="remplir_reser.PHP">Reserver</a></button>
        <p> kaya, Burkina Faso</p>
      </div>
    </div>
    <div class="popular__card">
      <img src="image\H18.jpg"/>
      <div class="popular__content">
        <div class="popular__card__header">
          <h4>Grâce Divine Auberge </h4>
          <h4>⭐⭐⭐</h4>
        </div>
        <button><a href="remplir_reser.PHP">Reserver</a></button>
        <p> kaya, Burkina Faso</p>
      </div>
    </div>
    <div class="popular__card">
      <img src="image\H19.jpg"/>
      <div class="popular__content">
        <div class="popular__card__header">
          <h4>Pacific Hôtel</h4>
          <h4>⭐⭐⭐⭐</h4>
        </div>
        <!--corp du site partie boutton--->
        <button><a href="remplir_reser.PHP">Reserver</a></button>

        <p> kaya, Burkina Faso</p>
      </div>
    </div>
    <div class="popular__card">
      <img src="image\C7.jpg"/>
      <div class="popular__content">
        <div class="popular__card__header">
          <h4>Chambre de l'hôtel ci-dessus</h4>
          <h4>XOF48800</h4>
        </div>
         <!--corp du site partie boutton--->
        <button><a href="remplir_reser.PHP">Reserver</a></button>

        <p> kaya, Burkina Faso</p>
      </div>
    </div>
    <div class="popular__card">
      <img src="image\C8.jpg"/>
      <div class="popular__content">
        <div class="popular__card__header">
          <h4>Chambre de l'hôtel ci-dessus</h4>
          <h4>XOF22000</h4>
        </div>
         <!--corp du site partie boutton--->
        <button><a href="remplir_reser.PHP">Reserver</a></button>
        
        <p> kaya, Burkina Faso</p>
      </div>
    </div>
    <div class="popular__card">
      <img src="image\C9.jpg"/>
      <div class="popular__content">
        <div class="popular__card__header">
          <h4>Chambre de l'hôtel ci-dessus</h4>
          <h4>XOF42000</h4>
        </div>
         <!--corp du site partie boutton--->
        <button><a href="remplir_reser.PHP">Reserver</a></button>

        <p>  kaya, Burkina Faso</p>
      </div>
    </div>
  </div>
</section>


 <!--corp du site partie client--->
<section class="client">
  <div class="section__container">
    <h2 class="section__header">💙💙L'avis de certains clients sur nos services💙💙</h2>
    <div class="client__grid">
      <div class="client__card">
        <img src="image/client-1.jpg" alt="client" />
       
          <h6>Ouedraogo Styve , 35 ans, oaugadougou</h6><br>
          <p class="client__card_text">
          J'ai utilisé les services de cette agence pour organiser un séjour à oaugadougou et j'ai été extrêmement satisfaite. 
          L'hôtel réservé était bien situé, propre et le personnel très accueillant. Les recommandations pour les restaurants
           et les visites étaient également excellentes. Je recommande vivement cette agence pour leur professionnalisme et leur
            attention aux détails.😁

        </p>
      </div>
      <div class="client__card">
      <img src="image/client-2.jpg"/>
      <h6>Samadoulgou Keyla, 29ans, Bobo Dioulasso</h6><br>
          <p class="client__card_text">
          Je ne peux que louer les services de cette agence hôtelière. J'ai réservé un séjour surprise pour l'anniversaire
           de mon mari à Bobo Dioulasso. Tout était parfait, de la réservation de l'hôtel au transport. Le personnel de l'agence
            était très à l'écoute et a su répondre à toutes mes attentes. Mon mari a adoré son cadeau et nous avons passé 
            un séjour inoubliable. Merci à toute l'équipe Mer.🙏
        </p>
      </div>
      <div class="client__card">
      <img src="image/client-3.jpg"/>
      <h6>Zougrana wisdome, 23 ans, koudougou</h6><br>
           <p class="client__card_text">
           Mon expérience avec cette agence hôtelière a été mitigée. Bien que l'hôtel était correct et le service client réactif,
           il y a eu quelques erreurs dans ma réservation. On m'avait promis une chambre avec vue sur la vegetation(parc forestier), mais j'ai fini avec
            une vue sur le parking. Après avoir signalé le problème, ils ont pu rectifier la situation, mais cela a pris du temps.
             Dans l'ensemble, le service est bon, mais il y a de la place pour des améliorations.👍🏼
          </p>
      </div>
    </div>
  </div>
</section>

 </nav>

<!--menu-->
<p>
<h2 class="menuu">💙💙Menu informations💙💙<br>💙💙choisir une option (puis cliquez ⬇)💙💙</h2>
<ul class="menu">
         <li class="a1"><a href="phpafficher_reser.PHP">Afficher les reservations</a></li>
         <li  class="a2"><a  href="afficher_client.PHP">Voir si je suis un client</a></li>
         <li  class="a3"><a href="remplir_reser.PHP">Effectuer une reservation</a></li>
    </ul>
</p>
<!--pied de page-->
<footer>
    <!--la class contenu du foote-->
   <div class="contenu-footer">
      <div class=" bloc footer-plan">
         <h3>Plan du site</h3>
         <ul class="liste-Service">
              <li><a href="index.PHP">Acceuil</a></li>
              <br>
              <li><a  href="prestation.PHP">prestations</a></li>
              <br>
              <li><a href="reservation.PHP">Reservation</a></li>
              <br>
              <li><a href="contact.PHP">Contact</a></li>
              <br>
              <li><a href="inscription.PHP">inscription</a></li>
         </ul>
      </div>
      <div class=" bloc footer-contact">
        <h3>Restons en contact</h3>
        <p>📲Tel 1: 52-87-50-41</p>
        <br>
        <p>📲Tel 2: 56-06-41-93</p>
        <br>
        <!--email-->
        <p><a href="mailto:decidaisomar@gmail.com" class="email">decidaisomar@gmail.com</a></p>
         <!--image footer--> 
         <br>
        <div class="im1"><img src="image\logo.jpg"></div>
      </div>
      <div class=" bloc footer-horaire">
        <h3>Nos Horaires</h3>
         <ul class="liste-horaire">
           <li>✔️ Lun 03h-20h</li>
           <br>
           <li>✔️ Mar 02h-22h</li>
           <br>
           <li>✔️ Mer 04h-19h</li>
           <br>
           <li>✔️Jeu 01h-21h</li>
           <br>
           <li>✔️ Ven 04h-00h</li>
           <br>
           <li>✔️ sam 05h-23h</li>
           <br>
           <li>✔️ dim 05h-18h</li>
         </ul>
      </div>
      <div class=" bloc footer-reseaux">
         <h3>Nos réseaux</h3>
         <!--les media-->
         <ul class="liste-media">
             <li><a href=" https://chat.whatsapp.com/LtbxbuFx7T59jWL2gUSONr" target="_blank"><img src="image/whatsapp.jpg"> <br>whatsapp</a></li>
             <li><a href="https://www.facebook.com/profile.php?id=61561028142293 " target="_blank"><img src="image/facebook.jpg"> <br>facebook </a></li>
             <li><a href="https://www.instagram.com/company_royal_palace?igsh=dWhlMmVoNmdreTVl" target="_blank"><img src="image/instagrame.jpg"> <br>instagrame</a></li>
          </ul>

      </div>
      <div class=" bloc footer-menbre">
         <h3>Menbres groupe</h3>
          <ul class="liste-menbre">
          <li><span>1.</span>Dzidziwu Dylan Omar</li>
             <br>
             <li><span>2.</span>DIARRA KEYLA LESLIE</li>
             <br>
             <li><span>3.</span>DEGBO-HOUMEY WISDOM MARCEL</li>
             <br>
             <li><span>4.</span>NIKIEMA ELVIS JETHRO</li>
             <br>
             <li><span>5.</span> MAIGA ABDOUL GABIROU MOUSSA</li>
             <br>
             <li><span>6.</span> OUEDRAOGO PUSDBA GILBERTINE</li>
          </ul>
      </div>
    </div>
    <!--la date-->
      <div class="date">
          <p>copyright : 2024</p>
      </div>
    <br>
</footer>
</div>
</body>
</html>